[package]
name = "server"
version = "0.1.0"
edition = "2021"
authors = ["Kozakura <@kozakura@misskey.kzkr.xyz>"]
license = "MIT OR Apache-2.0"
description = "cherrypick rmote files proxy"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-stream = "*"
axum = { version = "^0.6", features = ["headers","http2"] }
tokio = { version = "1.0", features = ["rt-multi-thread"] }
tokio-util = { version = "0.7.8", features = ["io"] }
futures = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }
headers = "^0.3.8"
serde = {version="^1.0.164",features=["derive"]}
serde_json ="1"
reqwest = { version = "0.11", default-features = false , features = ["stream","rustls-tls-webpki-roots"] }
uuid = { version = "1.8" , features = ["v4"] }
redis = { version = "0.25", features = ["tokio-comp"] }
urlencoding = "2.1.3"

[profile.release]
strip = true
opt-level = 3
lto = true
panic = "abort"

