version: "3"

services:
  server:
    build: .
    restart: always
    links:
      - redis
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "23725:23725"
    environment:
      - FILES_PROXY_CONFIG_PATH=/config/config.json
    networks:
      - internal_network
      - external_network
    volumes:
      - ./docker-config:/config:ro
    healthcheck:
      test: "./files-proxy ping"
      interval: 10s
      retries: 3

  redis:
    restart: always
    image: redis:7-alpine
    networks:
      - internal_network
    volumes:
      - ./redis:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      retries: 20


networks:
  internal_network:
    internal: true
  external_network:
